### ISSUE TITLE
docker-compose up failing

### ISSUE THREAD

**Issue by nazariyv** [guitargz/aidabot#1]
there is an issue with token.txt

I have created a Telegram bot, copied the access token and placed it both in the root

and in the src/token.txt

running docker-compose up gives me the following error

```
bot_1       | Traceback (most recent call last):
bot_1       |   File "/code/./aida.py", line 76, in <module>
bot_1       |     asyncio.run(main())
bot_1       |   File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
bot_1       |     return loop.run_until_complete(main)
bot_1       |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
bot_1       |     return future.result()
bot_1       |   File "/code/./aida.py", line 55, in main
bot_1       |     bot = Bot(token=password)
bot_1       |   File "/root/.local/lib/python3.9/site-packages/aiogram/bot/base.py", line 68, in __init__
bot_1       |     api.check_token(token)
bot_1       |   File "/root/.local/lib/python3.9/site-packages/aiogram/bot/api.py", line 71, in check_token
bot_1       |     raise exceptions.ValidationError(message)
bot_1       | aiogram.utils.exceptions.ValidationError: Token is invalid! It can't contains spaces.
```

Redis is starting fine

**Comment by guitargz** [comment]
Have you also changed the channel name for your bot in the /aida/src/aida.py?

MY_CHANNEL = '@aida_enelpi'

**Comment by nazariyv** [comment]
indeed, I have

**Comment by nazariyv** [comment]
can I log what key it is using somewhere?

**Comment by nazariyv** [comment]
can I log what key it is using somewhere?

**Comment by nazariyv** [comment]
noticed on line 44: pass_file = "/run/secrets/bot_token"

which is not token.txt. So I have created a file bot_token.txt as well. Maybe I should just use bot_token, instead?

**Comment by guitargz** [comment]
"/run/secrets/bot_token" is a location inside the Docker container. The docker-compose file takes care to copy the token.txt to "/run/secrets/bot_token" during the build. Are you running "docker-compose build" from the project root?

**Comment by nazariyv** [comment]
indeed, I am

**Comment by nazariyv** [comment]
is everything working fine for you when you follow the steps in the README with a fresh git clone?

Are you creating a Telegram bot for this, right? Because as far as I know creating a community is different from creating a bot. And I have implicitly assumes that for this repo to work, one must create a bot, not a community. Since once needs an access token.

**Comment by guitargz** [comment]
Correct, I created a bot with BotFather and got a token for it. Then the bot is added as admin to an existing channel where he is supposed to post. But in aida.py you enter the name of the channel where the bot will post (not the name of the bot).
Make sure the token is entered in token.txt in the format „number:token“ (as you get it from BotFather) without spaces.

**Comment by nazariyv** [comment]
Alright, I think I know the issue. I was adding the name of the bot, not the channel where the bot is supposed to be posting ;) Will try soon. Thank you.

**Comment by guitargz** [comment]
Hope it works. I will make it clearer in the readme, thanks.

**Comment by nazariyv** [comment]
seems to have done the trick. But now I am getting a traceback in stylegan:

```
stylegan_1  | Traceback (most recent call last):
stylegan_1  |   File "./sgan_gen.py", line 79, in <module>
stylegan_1  |     main()
stylegan_1  |   File "./sgan_gen.py", line 53, in main
stylegan_1  |     Gs = load_Gs(MODEL)
stylegan_1  |   File "./sgan_gen.py", line 31, in load_Gs
stylegan_1  |     raise Exception('Failed to find the model')
stylegan_1  | Exception: Failed to find the model
```

I have downloaded the model. Could this mean I have saved it in the wrong location? I have saved it in `stylegan/src`. I am not sure if this error is critical as it appears that other containers are working fine.

Is there a particular command on the bot to make it generate the picture and the text in the community channel?

thanks

**Comment by nazariyv** [comment]
figured this one out. MODEL const is named something something 40.pkl. But the downloaded file is something something 70.pkl

**Comment by nazariyv** [comment]
hmm says bot is not a member of the channel chat, even though he is an admin, any idea what this might be?

**Comment by nazariyv** [comment]
my bad, wrong channel name this time :) should work now. Thanks for your work :)
