### ISSUE TITLE
Is there a way to make it keep generating the images?

### ISSUE THREAD

**Issue by nazariyv** [guitargz/aidabot#2]
So far it appears that I need to restart the docker containers every single time.

**Comment by nazariyv** [comment]
so the sleep is in fact in seconds not in milliseconds, and another thing, I think finally will shut down the bot after the first run, so this should do the trick:

```
        #Post to Telegram
        disp = Dispatcher(bot=bot)
        disp.register_message_handler(start_handler, commands={"start", "restart"})
        await bot.send_photo(MY_CHANNEL, photos, caption)
        # await disp.start_polling()

        #wait
        await asyncio.sleep(10)
```

saying that. Just saw that gpt-2 returned unimaginably long bytecode on the third run

**Comment by nazariyv** [comment]
hmm, I think it must be some sort of dependency on gpt-2 API that rate-limits the number of requests? and that is why you had 21600. Which can only mean that perhaps the true delay must be set at something like 22 seconds? I will try that out.

**Comment by guitargz** [comment]
I wanted the bot to post every 21600 seconds - it keeps generating the images with this frequency. Will mention it in the readme as well.
